---
- name: Set-up Jenkins on required server
  hosts: JenkinsServer
  tasks:
    - name: Install required SW's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: openjdk-11-jdk,b: present,c: yes}
        - {a: git,b: present,c: no}
        - {a: maven,b: present,c: no}
    - name: Download Jenkins.jar
      get_url:
        url: https://get.jenkins.io/war-stable/2.462.3/jenkins.war
        dest: /tmp
- name: setting-up required SW's on QAProd servers
  hosts: servers
  tasks:
    - name: Installing tomcat10 & tomcat10-admin
      apt:
        name: "{{item.d}}"
        state: present
        update_cache: "{{item.e}}"
      with_items:
        - {d: tomcat10,e: yes}
        - {d: tomcat10-admin,e: no}
    - name: copy tomcat-user.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
      notify: Restart tomcat10
  handlers:
    - name: Restart tomcat10
      service:
        name: tomcat10
        state: restarted 
... 
