---
- name: executing when conditon
  hosts: all
  tasks:
    - name: checking f1 folder is available at /tmp location
      stat:
        path: /tmp/f1
      register: a
    - name: displaying/storing output of above module
      debug:
        var: a
    - name: creating a file f1 if f1 dire is not present
      file:
        name: /tmp/f1
        state: absent
      when: a.stat.exists == true
...

