---
- name: URL accessbale checking
  hosts: all
  tasks:
    - block:
      - name: URL aaccess checking 
        uri:
          url: http://172.31.43.11:8080
          status_code: 200
      - name: URL access checking on 2nd server
        uri:
          url: http://172.31.37.227:8080
          status_code: 200
      rescue:
        - name: URL access re-check on server1
          uri:
            url: http://172.31.43.11:9090
            status_code: 200
        - name: URL access re-check on server2
          uri:
            url: http://172.31.37.227:9090
            status_code: 200
        - name: replace 9090 with 8080
          replace:
            regexp: 9090
            replace: 8080
            path: /etc/tomcat10/server.xml
          notify: Restart tomcat10
  handlers:
    - name: Restart tomcat10
      service:
        name: tomcat10
        state: restarted
...
