---
- name: Nginx configuration
  hosts: all
  tasks:
    - name: Installing nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: copy index.html page
      copy:
        src: index.html
        dest: /usr/share/nginx/html
    - name: Restart
      service:
        name: nginx
        state: restarted
    - name: URL access check
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.35.26
        - http://172.31.35.103
...
