---
- name: executing handlers
  hosts: all
  tasks:
    - name: creatinf f3 /home/f3
      file:
        name: /home/f3
        state: touch
      notify: create f4
  handlers:
    - name: create f4
      file:
        name: /home/f4
        state: touch
...
